export const START_DOWNLOAD_GAME = "START_DOWNLOAD_GAME";
export const START_SEEDING = "START_SEEDING";
export const PAUSE_DOWNLOAD_GAME = "PAUSE_DOWNLOAD_GAME";
export const START_GAME = "START_GAME";
export const UNARCHIVE_GAME = "UNARCHIVE_GAME";
