export const ADD_TORRENT = "ADD_TORRENT";
export const ADD_TORRENT_SEED = "ADD_TORRENT_SEED";
export const UPDATE_TORRENT = "UPDATE_TORRENT";
export const TORRENT_DOWNLOADING = "TORRENT_DOWNLOADING";
export const UPDATE_TORRENT_INFOHASH = "UPDATE_TORRENT_INFOHASH";
export const UPDATE_TORRENT_PROGRESS = "UPDATE_TORRENT_PROGRESS";
export const NEXT_TORRENT_KEY_USED = "NEXT_TORRENT_KEY_USED";
export const TORRENT_DOWNLOADED = "TORRENT_DOWNLOADED";
export const STOP_TORRENTS = "STOP_TORRENTS";
export const CLEAR_TORRENTS = "CLEAR_TORRENTS";

export const UNARCHIVE_START = "UNARCHIVE_START";
export const UNARCHIVE_OK = "UNARCHIVE_OK";
export const UNARCHIVE_FAIL = "UNARCHIVE_FAIL";
export const UPDATE_GAME = "UPDATE_GAME";
